### ISSUE TITLE
flexvol driver as a container

### ISSUE THREAD

**Issue by khenidak** [khenidak/dysk#13]
We need - if possible ? - to have dysk flex vol driver as a container. Idea being, the 3 components that represents dysk on any given kubernetes cluster can be running either as daemon set for **dysk-installer** (which builds, install, and upgrade dysk) or directly via cli  ```docker run ... ``` command line such as the case of **dyskctl** and **dysk flex vol driver**

this will allow users to run dysk without modifying cluster bootstrap scripts (such as as-engine).
 
check https://github.com/khenidak/dysk/blob/master/tools/dysk_shortcuts.sh for ``` docker run ... ``` commands that wraps **dyskctl** and **dysk installer**

 
CC: @andyzhangx

**Comment by andyzhangx** [comment]
all the flexvolume scripts are run in kubelet image, so you could even not pass ENVIRONMENT var in agent VM to that kubelet container. So I don't think it will work. As I could find, all flexvolume scripts must be put in `<plugindir>/<vendor~driver>/<driver>` according to [Flexvolume doc](https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md)

And when kubelet run, we use docker volume mapping for flexvolume dir `/etc/kubernetes/volumeplugins`, so driver could be invoked from kubelet, that's way how flexvolume works.

```
ExecStart=/usr/bin/docker run \
...
  --volume=/etc/kubernetes/volumeplugins:/etc/kubernetes/volumeplugins:rw \
    ${KUBELET_IMAGE} \
      /hyperkube kubelet \
...
```

**Comment by khenidak** [comment]
Yeah I was thinking this today. Btw i started moving flex vol forward. Will push mount existing and lease management hopefully tomorrow

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andyzhangx** [comment]
@khenidak wait, are you modifying the flex volume script now? I am beginning to writing this feature: mount existing vhd... So you will write the script next?

**Comment by khenidak** [comment]
I just pushed a modified version of the volume driver. What we have now is:

0. PV reference an account name and page blob path (account name is validated to == secret account name)
1. consistent mount/unmount (Existing page blob)
2. Format disk if not formatted
3. Added to cli (option to create only)
4. Missing: Option in cli to create and pv (I will create this later)
5. Lease management via config maps (Can you own this)? I have documented a possible approach on top of the flexvol script
