### ISSUE TITLE
dysk - error mounting when secret.AccountName != volume.AccountName

### ISSUE THREAD

**Issue by khenidak** [khenidak/dysk#23]
Repro
Create secret (valid key) with account name: account01
Create volume (valid volume) with account name: accountnot01

line 73 of dysk script 
```
echo "ERR: volume is referencing the wrong account name Vol:${VOL_ACCOUNT_NAME} Secret:${ACCOUNTNAME}" >> $ERRORLOG
```
Generate error " $ERRORLOG: ambiguous redirect" during mount operation 

@andyzhangx

**Comment by andyzhangx** [comment]
let me do a quick fix, 5 min
