### ISSUE TITLE
dysk + CSI - Implementation Approach

### ISSUE THREAD

**Issue by khenidak** [khenidak/dysk#29]
- `dyskcsi` is a new stand alone executable with its `main.go` (along with `Makefile`) are saved in `/dyskcsi` new directory similar to `dyskctl` implementation. 1dyskcsi1 imports `/pkg/client` package 
- `dyskcsi` executable containers definition such as  `docker file` + `any build tooling` are saved in `/tools` directory. Similar to current containers. 
- csi tools (such as `daemonset`) will contain dysk kernel module installer container image as a side car. csi tools should be saved in `/kubernetes` directory.
- Root `Makefile` will be modified to reference `dyskcsi` and `csi tools` Makefile, similar to the exiting approach.

The latest version (and moving on) does not depend on leases for `read-only` dysks.  Hence here is the simplified process:

> The plugin should support `ReadMany` or `ReadWriteOnce` Modes.

# Provision
Call `Client.CreatePageBlob` function similar https://github.com/khenidak/dysk/blob/master/dyskctl/cmd/utils.go#L34 supplying the needed parameters. ~I will add `autoLease` parameter which you should set it to false to enable creation without leases.~ The `autoLease` flag must be set to `false` 

# Mount

## Read Only
Call `Client.Mount` similar to https://github.com/khenidak/dysk/blob/master/dyskctl/cmd/utils.go#L60 with `autoLease` and `breakLease` parameters set to `false`. This will mount the device as readonly with no leases placed on the page blob.

## Read/Write
Call `client.Mount` similar to  https://github.com/khenidak/dysk/blob/master/dyskctl/cmd/utils.go#L60 but set `autoLease` and `breakLease` parameters to `true` and `false`. This will automatically create the lease for you but you will not need to save it. 

> If the `pageblob` is already leased the above call will return an error. This protects the user against mounting dysk as read/write across multiple nodes.

## Unmount
Call `Client.Unmount` like https://github.com/khenidak/dysk/blob/master/dyskctl/cmd/cmds.go#L216 setting `breakLease` to `true`. This leaves the page blob `unleased` for future `mounts`  
  
> A lot of the above logic is already implemented in `dyskctl` command line check `/cmd/utils.go` and `/cmd/cmds.go`

@andyzhangx

**Comment by khenidak** [comment]
@andyzhangx just a small update, the `Client.CreatePageBlob` function already has a parameter for create *without lease*

**Comment by andyzhangx** [comment]
@khenidak Have you built a latest dysk installer image based on your new features now?

**Comment by khenidak** [comment]
Not yet. Will push image today.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by khenidak** [comment]
Pushed: khenidak/dysk-installer:0.5
Pushed: khenidak/dysk-cli:0.4

**Comment by khenidak** [comment]
dysk has been merged
