### ISSUE TITLE
Check in the /vendor/ folder to the repo

### ISSUE THREAD

**Issue by ehotinger** [khenidak/dysk#39]
So that a fresh clone will just work out of the box, with no need to run `dep ensure`. This also means removing the `*vendor*` in the `gitignore` - not sure why the `vendor` folder is being ignored. Numerous big projects follow this pattern anyways, a la https://github.com/kubernetes/kubernetes/tree/master/vendor

**Comment by khenidak** [comment]
@ritazh -- can you help answering this?

**Comment by ehotinger** [comment]
@ritazh I would also encourage moving `pkg` from the root to `dyskctl/pkg` - will require some cleanup of the `Makefile`s, but better to consolidate all the Go stuff. Happy to make PRs to fix both of these issues if you guys approve of them.

**Comment by khenidak** [comment]
i think `pkg` should remain where it is, it has the `client` library which is wrapped by `dyskctl` There are some users such as `kubernetes` csi which will use the `pkg/client` directly. Unless we have a strong reasons to move it
