### ISSUE TITLE
[WIP] Kubernetes/CSI example doesn't work as described

### ISSUE THREAD

**Issue by skinny** [khenidak/dysk#55]
I really like to try out the new CSI implementation of dysk , so I deployed a new (acs-engine based) cluster on Azure and followed the steps outlined here : https://github.com/khenidak/dysk/blob/master/kubernetes/csi/README.md

Below are some observations and/or problems on which I would like to get some help or answers :-)  :

- The installer deployment creates a `flex` namespace but the components (provisioner,attached,driver) are deployed in the `default` namespace and stay in `ContainerCreating`. After redeploying them in the `flex` namespace, all pods got to the 1/1 running state

- I deployed the PVC + POD from the examples. the PVC gets created just fine and also the underlying PV and the actual Azure blob is created perfectly imo. However the pod remains stuck in `ContainerCreating` with the following events : 

```  Warning  FailedScheduling        1m (x2 over 1m)   default-scheduler                pod has unbound PersistentVolumeClaims (repeated 2 times)
  Normal   Scheduled               1m                default-scheduler                Successfully assigned web-0 to k8s-default-34580619-1
  Normal   SuccessfulAttachVolume  1m                attachdetach-controller          AttachVolume.Attach succeeded for volume "kubernetes-dynamic-pv-087759f33c9311e8"
  Normal   SuccessfulMountVolume   1m                kubelet, k8s-default-34580619-1  MountVolume.SetUp succeeded for volume "default-token-kfflk"
  Warning  FailedMount             26s (x8 over 1m)  kubelet, k8s-default-34580619-1  MountVolume.MountDevice failed for volume "kubernetes-dynamic-pv-087759f33c9311e8" : rpc error: code = Unavailable desc = grpc: the connection is unavailable```
```
- The `hostpath` volume(s) that are used across the components (the ones pointing to the /var/kubelet/plugins directory) are failing with errors like `MountVolume.SetUp failed for volume "socket-dir" : hostPath type check failed: /var/lib/kubelet/plugins is not a directory` . Removing the `type: Directory` from the volume specification works around the issue but that doesn't sounds like a permanent solution. For the `/var/lib/kubelet/plugins/csi-dysk' that has the type of `DirectoryOrCreate` the error that is returned is the same : 

- There seems to be inconsistency between the `*-standard.yaml` deployment files and the regular ones. What are the `standard` ones for ? For example the path used in the `socket-dir` volume specification in the `*-standard` files is suffixed with `csi-dysk` which seems to be more correct according to the CSI specs (https://kubernetes-csi.github.io/docs/CSI-Kubernetes.html)

*I'll add more comments to this issue when I encounter more quirks*

Thanks for the great project btw, I am really looking forward to start actually using this!

**Comment by andyzhangx** [comment]
@skinny Thanks for trying, in the beginning, it all works in 1.10.0-beta4, while in v1.10.0, there is a awkward bug: [Containerized kubelet won't start pods with host path volumes that contains type field](https://github.com/kubernetes/kubernetes/issues/61801) which would make error like `MountVolume.SetUp failed for volume "socket-dir" : hostPath type check failed`.
Anyway, I am now trying to use a workaround deployment scripts to make it work, just stay tuned.

**Comment by skinny** [comment]
Ah, good to see that it was not me doing something wrong with that `hostPath` issue. Looking forward to your workaround/fix.

Any chance you can describe the purpose of the `*-standard.yaml` files ?

**Comment by andyzhangx** [comment]
`*-standard.yaml` should be the working one after https://github.com/kubernetes/kubernetes/issues/61801 is fixed, while due to this hostpath.type issue, I need to find a workaround.

**Comment by andyzhangx** [comment]
@skinny you could try this yaml now:
```
kubectl create -f https://raw.githubusercontent.com/khenidak/dysk/master/kubernetes/csi/nginx-pod-csi-dysk.yaml
```

Before that, you need to delete the original daemenset and statefulset:
```
kubectl delete ds csi-dysk
kubectl delete sts csi-provisioner
kubectl delete sts csi-attacher
```

**Comment by andyzhangx** [comment]
I have updated the doc, only one yaml file is needed now for installing dysk CSI components

**Comment by skinny** [comment]
will try it tonight!

**Comment by skinny** [comment]
First tests with the new setup look promising .. both static and dynamic provisioning seem to work fine with my tests! 🥇  However I could use an answer/statement about the namespaces (see above)

**Comment by skinny** [comment]
One thing that is not working smoothly (yet) is re-using an existing PVC.

1. Create PVC
2. Create pod using PVC
3. Destroy pod, but keeping PVC
4. Redeploy pod (same yaml) 
5. pod is stuck in 'ContainerCreating'. The blob lease state is "broken" from within the Azure portal
6. After 5-10 minutes, the PVC is properly attached to the pod and Running

**Comment by skinny** [comment]
Thanks @andyzhangx for your work, much appreciated! I'm now testing more especially with the deletion of pods/volumes. Sometimes it looks like I run into https://github.com/khenidak/dysk/issues/57 too.

imo, this issue can be closed for now and will (re)open ones for more specific issues
