### ISSUE TITLE
Support for premium storage

### ISSUE THREAD

**Issue by khenidak** [khenidak/dysk#6]
Repo:
Create premium storage account (v2). 
Try mounting disks (from said storage account)

Dysk flags the disks as catastrophe immediately - Suspect: Storage REST API authN consistency.

**Comment by andyzhangx** [comment]
is it also support managed disk since AKS only use managed disk now. Thanks.

**Comment by khenidak** [comment]
Thanks Andy!

Dysk uses page blob directly from the user VM. Managed disks wraps page blobs calls in the host. dysk will work irrespective of aks or the location of vm for that matter (even on prem).

The catch is obviously having the module installed.

**Comment by khenidak** [comment]
Confirmed - SharedKeyLite is not authenticating successfully with Premium Storage Accounts (v1 + V2). Shared the findings with storage team

**Comment by andyzhangx** [comment]
@khenidak yes, I have tried on managed k8s cluster, it works well. Will share you a step-by-step doc soon.

**Comment by khenidak** [comment]
Andy you are awesome! :-)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by squillace** [comment]
repro here before I found this issue: 

![premiumdiskfailure](https://user-images.githubusercontent.com/1422718/34661879-6927e816-f401-11e7-9d65-cb9b951783da.png)

**Comment by khenidak** [comment]
Premium SKU is now supported by https://github.com/khenidak/dysk/commit/166871c046f8719516f7bb81640a2b5d50868605
