### ISSUE TITLE
driver name csi-dysk not found in the list of registered CSI drivers Events

### ISSUE THREAD

**Issue by mvvveen** [khenidak/dysk#64]
Since AKS version 1.12 i get this error message.

driver name csi-dysk not found in the list of registered CSI drivers

I have tried reinstalling dysk but without success.

Could it be a similar issue to this one?
https://github.com/rancher/longhorn/issues/310

**Comment by sharkymcdongles** [comment]
I also have this same error. Did you ever find a solution? I am on 1.13 k8s, and I cannot figure the solution out yet.

**Comment by sharkymcdongles** [comment]
@mvvveen

**Comment by mvvveen** [comment]
No unfortunately not. I'm afraid @khenidak  is not actively maintaining this any longer.
